humanoid_walking/params/dt:        0.07
humanoid_walking/params/lip_dt:    0.005
humanoid_walking/params/tS:        0.1
humanoid_walking/params/tD:        0.01
humanoid_walking/params/stepH:     0.04
humanoid_walking/params/zCCorr:    1
humanoid_walking/cmd/vx:        0
humanoid_walking/cmd/vy:        0
humanoid_walking/cmd/vz:        0
humanoid_walking/cmd/slope:     4
humanoid_walking/ctrl/delayL:    1
humanoid_walking/ctrl/delayR:    1
humanoid_walking/ctrl/delayAll:  3.1860000000000004
humanoid_walking/cmd/walk_flag: false
